#165273477 Add user crud functionality
andela/ah-backend-invictus pull request #10
Opened 2019-04-25 18:49 UTC by KabohaJeanMark

**What does this PR do?**
This PR enables users to access crud functionality for the article.

*Tasks*
- add create article feature
- add retrieve one or all their articles feature
- add update article feature
- add delete article feature
- add unique article slugs automatically added to articles if they don't exist

*How to test it?*
Sign up and log in to access the articles routes.

Article endpoints
## Endpoints
|HTTP Header   | Endpoints                                            | Functionality                               |                             
|---------------|-------------------------------------|:------------------------------:|
|    POST          |```/api/article/```                                  |```Creates an article```             |
|    GET             |```/api/article/```                                  |```Gets an article```                  |
|    GET             |   ```/api/article/<article_id>```           |```Gets all articles``                   |
|    PUT             | ```/api/article/<article_id>```             |```Updates specific article```   | 
|    DELETE       |```/api/article/<article_id>```              |```Deletes specific article```     |

*Create an article*
<img width="1130" alt="Screen Shot 2019-04-25 at 9 14 53 PM" src="https://user-images.githubusercontent.com/44635784/56758548-95ab4000-679f-11e9-8d76-48a1a5a31814.png">

*Get all the articles*
<img width="1110" alt="Screen Shot 2019-04-25 at 9 24 44 PM" src="https://user-images.githubusercontent.com/44635784/56759036-aa3c0800-67a0-11e9-8082-599d193d6de1.png">

*Get a specific article*
<img width="1132" alt="Screen Shot 2019-04-25 at 9 27 29 PM" src="https://user-images.githubusercontent.com/44635784/56759190-1880ca80-67a1-11e9-9c7e-c3f94b8855ab.png">

*Delete a specific article*
<img width="1127" alt="Screen Shot 2019-04-25 at 9 29 22 PM" src="https://user-images.githubusercontent.com/44635784/56759261-3b12e380-67a1-11e9-87e1-d24eeee28339.png">

*Update a specific article*
<img width="1120" alt="Screen Shot 2019-04-25 at 9 31 03 PM" src="https://user-images.githubusercontent.com/44635784/56759356-77deda80-67a1-11e9-8299-5064e874fda8.png">

Creating a story with the same title and the unique slug changes
Initial creation
<img width="1109" alt="Screen Shot 2019-04-25 at 9 33 40 PM" src="https://user-images.githubusercontent.com/44635784/56759576-f20f5f00-67a1-11e9-836f-5ecc5be07ea2.png">

Change in slug with story having same title
<img width="274" alt="Screen Shot 2019-04-25 at 9 34 14 PM" src="https://user-images.githubusercontent.com/44635784/56759582-f5a2e600-67a1-11e9-8f0f-94282c27b37f.png">

Further slug update
<img width="283" alt="Screen Shot 2019-04-25 at 9 34 29 PM" src="https://user-images.githubusercontent.com/44635784/56759588-f8054000-67a1-11e9-82f7-13cffb025df8.png">

[#165273477](https://www.pivotaltracker.com/story/show/165273477)

2019-04-26 02:40 UTC, mwinel commented
@KabohaJeanMark please endeavour to create appropriate PR titles. e.g; `Add articles crud functionality` instead of `Add user crud functionality`

2019-04-26 02:50 UTC, mwinel requested changes
Please, lint your code to make it more readable and maintainable. You can use either flake8 or pylint and if you so wish, use both of them.

2019-04-26 02:50 UTC, mwinel commented on authors/apps/articles/serializers.py
> +        read_only_fields = ('created_at','updated_at','favorited','favorite_count','slug')
Endeavour to lint your code before you push to avoid no newline errors, and crowded code.

2019-04-26 02:50 UTC, mwinel commented on authors/apps/articles/views.py
> +from django.shortcuts import render
@KabohaJeanMark avoid unnecessary and unused imports.

2019-04-29 06:18 UTC, sanya-kenneth requested changes

2019-04-29 06:18 UTC, sanya-kenneth commented on authors/apps/articles/models.py
> +
Please remove extra white space on lines 4 and 13 in your models.py file

2019-04-29 06:18 UTC, sanya-kenneth commented on authors/apps/articles/models.py
> +pre_save.connect(slug_generator, sender=Article)
Add an empty line at the end of the file. Please do this for all your files

2019-04-29 06:18 UTC, sanya-kenneth commented on authors/apps/articles/serializers.py
> +
please remove white space on line 11 in serializers.py

2019-04-29 07:51 UTC, archibishop commented on authors/apps/articles/tests/tests_articles.py
> +        """Initialize setup."""
@KabohaJeanMark Lets use fixtures here sync up with @mwinel and @3Nakajugo. Left a similar comment on their pr's.

2019-04-29 07:59 UTC, archibishop commented on authors/apps/articles/serializers.py
> +class ArticleSerializer(serializers.ModelSerializer):
@KabohaJeanMark Some of the fields are required as bare minimum for an article. Do you cater for this anywhere. I don't see any validation for such.

####Screenshot
<img width="486" alt="Screen Shot 2019-04-29 at 10 56 27" src="https://user-images.githubusercontent.com/36948493/56882900-bdcfc300-6a6d-11e9-8808-00f081ceced4.png">

2019-04-29 08:00 UTC, archibishop commented on authors/apps/articles/tests/tests_articles.py
> +        """Ensure we cannot create a new article object with missing title."""
@KabohaJeanMark Follow TDD. Each test should be testing for only one scenario.

2019-04-29 08:26 UTC, archibishop commented
@KabohaJeanMark Fix your PR title

2019-04-29 08:47 UTC, archibishop commented
@KabohaJeanMark The author name should be updated automatically using the request object instead of the user to send it as part of the Json object when creating an article.

2019-04-29 09:17 UTC, archibishop commented
@KabohaJeanMark Look into overriding the default methods e.g retrieve, get_object so you could return  a more descriptive message. e.g "Article Not Found" 

#### Description
*Current error message returned*
<img width="312" alt="Screen Shot 2019-04-29 at 12 13 40" src="https://user-images.githubusercontent.com/36948493/56886803-7dc20d80-6a78-11e9-86b4-b38e923e36b4.png">

2019-04-29 09:24 UTC, archibishop commented
@KabohaJeanMark When an article is deleted, no message is shown. Something like `Article has been successfully removed` should be returned so that the user can know the action was successful.

2019-04-29 14:41 UTC, mwinel requested changes
Please make sure your response is as per the `README.md`
```
{
  "article": {
    "slug": "how-to-train-your-dragon",
    "title": "How to train your dragon",
    "description": "Ever wonder how?",
    "body": "It takes a Jacobian",
    "tagList": ["dragons", "training"],
    "createdAt": "2016-02-18T03:22:56.637Z",
    "updatedAt": "2016-02-18T03:48:35.824Z",
    "favorited": false,
    "favoritesCount": 0,
    "author": {
      "username": "jake",
      "bio": "I work at statefarm",
      "image": "https://i.stack.imgur.com/xHWG8.jpg",
      "following": false
    }
  }
}
```

2019-04-29 14:46 UTC, engjames requested changes
Nice work but Read through the README.md file and return data in the format suggested. Specifically for articles.

2019-04-30 05:26 UTC, mwinel approved these changes

2019-04-30 07:02 UTC, joelmugaya commented on authors/apps/articles/tests/test_article_crud.py
> +        url = '/api/users/login/'
It looks to me like you are not using these lines of code

2019-04-30 07:33 UTC, engjames approved these changes

2019-04-30 11:58 UTC, archibishop approved these changes
@KabohaJeanMark LGTM I am merging this.

2019-04-30 12:01 UTC, merged