#165273495 User should be able to like and revert a previous like on a comment
andela/ah-backend-invictus pull request #26
Opened 2019-05-06 14:16 UTC by engjames

**What does this PR do?**
- Likes and unlikes a comment

**Description of the task to be completed**
- User should be able to like and unlike a comment
 http://127.0.0.1:8000/api/articles/1/comments/2/like/
The URL likes or unlikes a comment of id 2 on the article of id 1.
**Like a comment**
![image](https://user-images.githubusercontent.com/44478973/57230480-192b2380-7021-11e9-9e3f-e6e3f422181f.png)
**Get a comment and check the likes_counter. It has been incremented by 1**
![image](https://user-images.githubusercontent.com/44478973/57230619-6c9d7180-7021-11e9-835a-ed921c8fc9c8.png)
**Unlike a comment**
![image](https://user-images.githubusercontent.com/44478973/57230678-93f43e80-7021-11e9-87e6-8899934c6fc7.png)
**Get a comment and check the likes_counter. It has been decremented by 1**
![image](https://user-images.githubusercontent.com/44478973/57230842-ea617d00-7021-11e9-839c-d670129c03ce.png)

**What are the relevant Pivotal Tracker stories?**
[#165273495](https://www.pivotaltracker.com/story/show/165273495)

2019-05-06 20:18 UTC, sanya-kenneth approved these changes

2019-05-07 05:39 UTC, mwinel submitted a review, later dismissed
LGTM, this is ready for a merge.

2019-05-07 05:44 UTC, KabohaJeanMark approved these changes
This looks good to me. Good job @engjames. However, I am not sure why the branch is not being deployed.

2019-05-07 05:44 UTC, archibishop commented
@engjames Write tests.
<img width="1033" alt="Screen Shot 2019-05-07 at 08 44 04" src="https://user-images.githubusercontent.com/36948493/57274568-57b5f200-70a4-11e9-97da-c7d845d063a8.png">

2019-05-07 06:01 UTC, mwinel requested changes
Please write unit tests for your feature ASAP....

2019-05-07 06:07 UTC, KabohaJeanMark reviewed
Good work on the functionality. Please, just add a few unit tests.

2019-05-07 06:09 UTC, KabohaJeanMark requested changes
Please add unit tests to test the response messages and status codes when liking, liking again to cancel your like or attempting to like one's own article

2019-05-07 09:44 UTC, mwinel approved these changes

2019-05-07 16:15 UTC, mwinel approved these changes
LGTM, this is ready for a merge.

2019-05-07 16:18 UTC, 3Nakajugo approved these changes

2019-05-07 16:20 UTC, sanya-kenneth approved these changes

2019-05-08 08:51 UTC, archibishop commented on authors/apps/comments/views.py
> +            return Response({"Message":"True, You have ever liked this comment."},
This could be a better response.
```suggestion
            return Response({"status":true},
```

2019-05-08 08:51 UTC, archibishop commented on authors/apps/comments/views.py
> +        return Response({"Message":"False, You have never liked this comment."},
```suggestion
        return Response({"status":false},
```

2019-05-08 11:28 UTC, archibishop approved these changes
@engjames LGTM i am merging you in.

2019-05-08 11:31 UTC, merged